name = "Jitsuin RKVST"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Multi-Party Trust Automation API, Powered by Blockchain "
homepage = "https://jitsuin.com/"
tags = ["landing page", "documentation", "jitsuin", "blockchain", "multi-party", "trust", "data-assurance""]
features = ["landing page", "documentation", "jitsuin", "blockchain", "multi-party", "trust", "data-assurance"]
min_version = "0.75.0"

[author]
  name = "Will Godfrey"
